### ISSUE TITLE
Error when I want to create or update a news

### ISSUE THREAD

**Issue by gergo85** [TimFoerster/octobercms-news-pdf#3]
![error](https://cloud.githubusercontent.com/assets/2959112/26100067/19aa6f86-3a2d-11e7-8220-4ea72d340ad0.jpg)

**Comment by TimFoerster** [comment]
sorry, my fault, update and try it again :)

**Comment by gergo85** [comment]
Thank you! It works perfectly. Please update the plugin on the October Market too.

**Comment by TimFoerster** [comment]
ups, forgot the hook, thanks
