### ISSUE TITLE
How it works ?

### ISSUE THREAD

**Issue by ajmanco** [TimFoerster/octobercms-news-pdf#4]
hi . thanks a lot for this usefull plugin . but i have a question . You have a sample invoice pdf template in here . and i want to create a new one and put my news content in the output as a pdf . what i should put in html template to work in news and show my contents and image that i used in news plugin ? Im confused . for example i write this : <h2 class="post-title">{{ post.title }}</h2> in html template to show my news title . but my PDF output is blank . pleas help me .

And another question is : your plugin dont support UTF8 caracters ? because in output PDF it shows ???? caracters instead of words .

thanks

**Comment by ajmanco** [comment]
Any answer ???!!

**Comment by TimFoerster** [comment]
@ajmanco sorry for the late response, I had some days off.
There are 2 variables only in the template. It is `title` and `content`.
See here: https://github.com/TimFoerster/octobercms-news-pdf/blob/3c9bb9d85bfc42ad4d536c012dabf3ee25e2b4fa/models/NewsPdf.php#L52

Regarding utf8 characters have a look here: https://github.com/mplodowski/dynamicpdf-plugin/issues/5

**Comment by ajmanco** [comment]
Tnx for response .  
Regarding your answere about UTF8  characters , i try your solutions. it works but with another problem . 
I use Persian ( right to left ) characters  , but i think your plugin dont work with rtl characters . It shows characters now but  separately . I search about this and find  " TCPDF " packages . It works as well with UTF8 and RTL characters .

**Comment by TimFoerster** [comment]
This plugin just combines the richeditor of octobercms and dompdf plugin.
Ask your questions about pdf support there.
The rtl problem is already listed there: https://github.com/barryvdh/laravel-dompdf/issues/471
